behaviors:
  CoOpDefender:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 64
    summary_freq: 100000

    # self-play
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      team_change: 100000
      #swap steps should be (teamsize / other_teamsize) * (teamchange / number_swaps_wanted)
      swap_steps: 10000

  CoOpAttacker:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 64
    summary_freq: 100000

    # self-play 
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      team_change: 100000
      #swap steps should be (teamsize / other_teamsize) * (teamchange / number_swaps_wanted)
      swap_steps: 2000

environment_parameters:
  defender_count: 3.0
  attacker_count: 1.0
  defender_speed: 1.0
  attacker_speed:
    curriculum:
      - name: AttackerLearn # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: CoOpAttacker
          signal_smoothing: true
          min_lesson_length: 10
          threshold: 0.5
        value: 1.5
      - name: AttackerSlow # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: CoOpDefender
          signal_smoothing: true
          min_lesson_length: 10
          threshold: 0.5
        value: .1
      - name: Improve
        value: 1.5
